#!/usr/bin/env python3
import tiktoken
import sys
def main():
    s = sys.stdin.read()
    enc = tiktoken.encoding_for_model("gpt-4")
    print(len(enc.encode(s)))
    return
    enc = tiktoken.get_encoding("cl100k_base")
    assert enc.decode(enc.encode("hello world")) == "hello world"

if __name__ == "__main__":
    main()
