#!/usr/bin/env python3
import sys

start = False
end = False
buffer = []

for line in sys.stdin:
    stripped_line = line.rstrip()
    if stripped_line.startswith('```'):
        if start and not end:
            end = True
        elif not start:
            start = True
        elif start and end:
            raise ValueError("More than two lines that start with ```")
    elif start and not end:
        buffer.append(stripped_line)

if start and not end:
    raise ValueError("End line that starts with ``` not found")

for line in buffer:
    print(line)
